// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ffi.dart';
import 'api/ffi_types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustSyncApi extends BaseEntrypoint<RustSyncApiApi, RustSyncApiApiImpl, RustSyncApiWire> {
                  @internal
                  static final instance = RustSyncApi._();

                  RustSyncApi._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustSyncApiApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustSyncApiApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustSyncApiApiImpl, RustSyncApiWire> get apiImplConstructor => RustSyncApiApiImpl.new;

                  @override
                  WireConstructor<RustSyncApiWire> get wireConstructor => RustSyncApiWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    
                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.12.0';

                  @override
                  int get rustContentHash => -922685216;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'sync_core',
                    ioDirectory: 'native/sync-core/target/release/',
                    webPrefix: 'pkg/',
                    wasmBindgenName: 'wasm_bindgen',
                  );
                }
                

                abstract class RustSyncApiApi extends BaseApi {
                  Future<CloudAlbumCheckResultFfi> crateApiFfiCheckCloudAlbumDirs({required String baseUri });

Future<void> crateApiFfiCreateCloudAlbumDirs({required String baseUri });

Future<void> crateApiFfiDisposeSyncEngine();

Future<SyncSummaryFfi> crateApiFfiForceSync();

Future<SyncConfigFfi> crateApiFfiGetSyncConfig();

Future<SyncStatusFfi> crateApiFfiGetSyncStatus();

Future<void> crateApiFfiHydrateFile({required String localPath });

Future<void> crateApiFfiInitSyncEngine({required SyncConfigFfi config });

Future<void> crateApiFfiPauseSync();

Future<void> crateApiFfiResumeSync();

Future<void> crateApiFfiStartContinuousSync();

Future<SyncSummaryFfi> crateApiFfiStartInitialSync();

Future<void> crateApiFfiStopSync();

Future<void> crateApiFfiSyncAlbumToCloud({required List<String> albumPaths , required String remoteDcimUri });

Future<void> crateApiFfiUpdateSyncConfig({required SyncConfigFfi config });

Future<void> crateApiFfiUpdateTokens({required String accessToken });


                }
                

                class RustSyncApiApiImpl extends RustSyncApiApiImplPlatform implements RustSyncApiApi {
                  RustSyncApiApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<CloudAlbumCheckResultFfi> crateApiFfiCheckCloudAlbumDirs({required String baseUri })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(baseUri, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_cloud_album_check_result_ffi,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiCheckCloudAlbumDirsConstMeta,
            argValues: [baseUri],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiCheckCloudAlbumDirsConstMeta => const TaskConstMeta(
            debugName: "check_cloud_album_dirs",
            argNames: ["baseUri"],
        );
        

@override Future<void> crateApiFfiCreateCloudAlbumDirs({required String baseUri })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(baseUri, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiCreateCloudAlbumDirsConstMeta,
            argValues: [baseUri],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiCreateCloudAlbumDirsConstMeta => const TaskConstMeta(
            debugName: "create_cloud_album_dirs",
            argNames: ["baseUri"],
        );
        

@override Future<void> crateApiFfiDisposeSyncEngine()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiDisposeSyncEngineConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiDisposeSyncEngineConstMeta => const TaskConstMeta(
            debugName: "dispose_sync_engine",
            argNames: [],
        );
        

@override Future<SyncSummaryFfi> crateApiFfiForceSync()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_sync_summary_ffi,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiForceSyncConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiForceSyncConstMeta => const TaskConstMeta(
            debugName: "force_sync",
            argNames: [],
        );
        

@override Future<SyncConfigFfi> crateApiFfiGetSyncConfig()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_sync_config_ffi,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiGetSyncConfigConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiGetSyncConfigConstMeta => const TaskConstMeta(
            debugName: "get_sync_config",
            argNames: [],
        );
        

@override Future<SyncStatusFfi> crateApiFfiGetSyncStatus()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_sync_status_ffi,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiGetSyncStatusConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiGetSyncStatusConstMeta => const TaskConstMeta(
            debugName: "get_sync_status",
            argNames: [],
        );
        

@override Future<void> crateApiFfiHydrateFile({required String localPath })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(localPath, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiHydrateFileConstMeta,
            argValues: [localPath],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiHydrateFileConstMeta => const TaskConstMeta(
            debugName: "hydrate_file",
            argNames: ["localPath"],
        );
        

@override Future<void> crateApiFfiInitSyncEngine({required SyncConfigFfi config })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_sync_config_ffi(config, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiInitSyncEngineConstMeta,
            argValues: [config],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiInitSyncEngineConstMeta => const TaskConstMeta(
            debugName: "init_sync_engine",
            argNames: ["config"],
        );
        

@override Future<void> crateApiFfiPauseSync()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiPauseSyncConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiPauseSyncConstMeta => const TaskConstMeta(
            debugName: "pause_sync",
            argNames: [],
        );
        

@override Future<void> crateApiFfiResumeSync()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiResumeSyncConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiResumeSyncConstMeta => const TaskConstMeta(
            debugName: "resume_sync",
            argNames: [],
        );
        

@override Future<void> crateApiFfiStartContinuousSync()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiStartContinuousSyncConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiStartContinuousSyncConstMeta => const TaskConstMeta(
            debugName: "start_continuous_sync",
            argNames: [],
        );
        

@override Future<SyncSummaryFfi> crateApiFfiStartInitialSync()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_sync_summary_ffi,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiStartInitialSyncConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiStartInitialSyncConstMeta => const TaskConstMeta(
            debugName: "start_initial_sync",
            argNames: [],
        );
        

@override Future<void> crateApiFfiStopSync()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiStopSyncConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiStopSyncConstMeta => const TaskConstMeta(
            debugName: "stop_sync",
            argNames: [],
        );
        

@override Future<void> crateApiFfiSyncAlbumToCloud({required List<String> albumPaths , required String remoteDcimUri })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_String(albumPaths, serializer);
sse_encode_String(remoteDcimUri, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiSyncAlbumToCloudConstMeta,
            argValues: [albumPaths, remoteDcimUri],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiSyncAlbumToCloudConstMeta => const TaskConstMeta(
            debugName: "sync_album_to_cloud",
            argNames: ["albumPaths", "remoteDcimUri"],
        );
        

@override Future<void> crateApiFfiUpdateSyncConfig({required SyncConfigFfi config })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_sync_config_ffi(config, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiUpdateSyncConfigConstMeta,
            argValues: [config],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiUpdateSyncConfigConstMeta => const TaskConstMeta(
            debugName: "update_sync_config",
            argNames: ["config"],
        );
        

@override Future<void> crateApiFfiUpdateTokens({required String accessToken })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(accessToken, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_sync_error_ffi,
        )
        ,
            constMeta: kCrateApiFfiUpdateTokensConstMeta,
            argValues: [accessToken],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiFfiUpdateTokensConstMeta => const TaskConstMeta(
            debugName: "update_tokens",
            argNames: ["accessToken"],
        );
        



                  @protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected SyncConfigFfi dco_decode_box_autoadd_sync_config_ffi(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_sync_config_ffi(raw); }

@protected CloudAlbumCheckResultFfi dco_decode_cloud_album_check_result_ffi(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return CloudAlbumCheckResultFfi(dcimExists: dco_decode_bool(arr[0]),
picturesExists: dco_decode_bool(arr[1]),
dcimUri: dco_decode_opt_String(arr[2]),
picturesUri: dco_decode_opt_String(arr[3]),); }

@protected List<String> dco_decode_list_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_String).toList(); }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected String? dco_decode_opt_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_String(raw); }

@protected SyncConfigFfi dco_decode_sync_config_ffi(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 10) throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
                return SyncConfigFfi(baseUrl: dco_decode_String(arr[0]),
accessToken: dco_decode_String(arr[1]),
localRoot: dco_decode_String(arr[2]),
remoteRoot: dco_decode_String(arr[3]),
syncMode: dco_decode_String(arr[4]),
conflictStrategy: dco_decode_String(arr[5]),
maxConcurrentTransfers: dco_decode_u_32(arr[6]),
bandwidthLimitKbps: dco_decode_u_64(arr[7]),
excludedPaths: dco_decode_list_String(arr[8]),
selectiveDirs: dco_decode_list_String(arr[9]),); }

@protected SyncErrorFfi dco_decode_sync_error_ffi(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return SyncErrorFfi_NotInitialized();
case 1: return SyncErrorFfi_NetworkError(message: dco_decode_String(raw[1]),);
case 2: return SyncErrorFfi_DiskFull(needed: dco_decode_u_64(raw[1]),available: dco_decode_u_64(raw[2]),);
case 3: return SyncErrorFfi_AuthError(message: dco_decode_String(raw[1]),);
case 4: return SyncErrorFfi_ConflictError(count: dco_decode_u_32(raw[1]),);
case 5: return SyncErrorFfi_InternalError(message: dco_decode_String(raw[1]),);
                default: throw Exception("unreachable");
            } }

@protected SyncStatusFfi dco_decode_sync_status_ffi(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 9) throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
                return SyncStatusFfi(state: dco_decode_String(arr[0]),
syncedFiles: dco_decode_u_64(arr[1]),
totalFiles: dco_decode_u_64(arr[2]),
uploadingCount: dco_decode_u_32(arr[3]),
downloadingCount: dco_decode_u_32(arr[4]),
conflictCount: dco_decode_u_32(arr[5]),
errorCount: dco_decode_u_32(arr[6]),
lastSyncTime: dco_decode_opt_String(arr[7]),
errorMessage: dco_decode_opt_String(arr[8]),); }

@protected SyncSummaryFfi dco_decode_sync_summary_ffi(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
                return SyncSummaryFfi(uploaded: dco_decode_u_32(arr[0]),
downloaded: dco_decode_u_32(arr[1]),
conflicts: dco_decode_u_32(arr[2]),
skipped: dco_decode_u_32(arr[3]),
deletedLocal: dco_decode_u_32(arr[4]),
deletedRemote: dco_decode_u_32(arr[5]),
durationMs: dco_decode_u_64(arr[6]),); }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected BigInt dco_decode_u_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected SyncConfigFfi sse_decode_box_autoadd_sync_config_ffi(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_sync_config_ffi(deserializer)); }

@protected CloudAlbumCheckResultFfi sse_decode_cloud_album_check_result_ffi(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_dcimExists = sse_decode_bool(deserializer);
var var_picturesExists = sse_decode_bool(deserializer);
var var_dcimUri = sse_decode_opt_String(deserializer);
var var_picturesUri = sse_decode_opt_String(deserializer);
return CloudAlbumCheckResultFfi(dcimExists: var_dcimExists, picturesExists: var_picturesExists, dcimUri: var_dcimUri, picturesUri: var_picturesUri); }

@protected List<String> sse_decode_list_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <String>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_String(deserializer)); }
        return ans_;
         }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected String? sse_decode_opt_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_String(deserializer));
            } else {
                return null;
            }
             }

@protected SyncConfigFfi sse_decode_sync_config_ffi(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_baseUrl = sse_decode_String(deserializer);
var var_accessToken = sse_decode_String(deserializer);
var var_localRoot = sse_decode_String(deserializer);
var var_remoteRoot = sse_decode_String(deserializer);
var var_syncMode = sse_decode_String(deserializer);
var var_conflictStrategy = sse_decode_String(deserializer);
var var_maxConcurrentTransfers = sse_decode_u_32(deserializer);
var var_bandwidthLimitKbps = sse_decode_u_64(deserializer);
var var_excludedPaths = sse_decode_list_String(deserializer);
var var_selectiveDirs = sse_decode_list_String(deserializer);
return SyncConfigFfi(baseUrl: var_baseUrl, accessToken: var_accessToken, localRoot: var_localRoot, remoteRoot: var_remoteRoot, syncMode: var_syncMode, conflictStrategy: var_conflictStrategy, maxConcurrentTransfers: var_maxConcurrentTransfers, bandwidthLimitKbps: var_bandwidthLimitKbps, excludedPaths: var_excludedPaths, selectiveDirs: var_selectiveDirs); }

@protected SyncErrorFfi sse_decode_sync_error_ffi(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: return SyncErrorFfi_NotInitialized();case 1: var var_message = sse_decode_String(deserializer);
return SyncErrorFfi_NetworkError(message: var_message);case 2: var var_needed = sse_decode_u_64(deserializer);
var var_available = sse_decode_u_64(deserializer);
return SyncErrorFfi_DiskFull(needed: var_needed, available: var_available);case 3: var var_message = sse_decode_String(deserializer);
return SyncErrorFfi_AuthError(message: var_message);case 4: var var_count = sse_decode_u_32(deserializer);
return SyncErrorFfi_ConflictError(count: var_count);case 5: var var_message = sse_decode_String(deserializer);
return SyncErrorFfi_InternalError(message: var_message); default: throw UnimplementedError(''); }
             }

@protected SyncStatusFfi sse_decode_sync_status_ffi(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_state = sse_decode_String(deserializer);
var var_syncedFiles = sse_decode_u_64(deserializer);
var var_totalFiles = sse_decode_u_64(deserializer);
var var_uploadingCount = sse_decode_u_32(deserializer);
var var_downloadingCount = sse_decode_u_32(deserializer);
var var_conflictCount = sse_decode_u_32(deserializer);
var var_errorCount = sse_decode_u_32(deserializer);
var var_lastSyncTime = sse_decode_opt_String(deserializer);
var var_errorMessage = sse_decode_opt_String(deserializer);
return SyncStatusFfi(state: var_state, syncedFiles: var_syncedFiles, totalFiles: var_totalFiles, uploadingCount: var_uploadingCount, downloadingCount: var_downloadingCount, conflictCount: var_conflictCount, errorCount: var_errorCount, lastSyncTime: var_lastSyncTime, errorMessage: var_errorMessage); }

@protected SyncSummaryFfi sse_decode_sync_summary_ffi(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_uploaded = sse_decode_u_32(deserializer);
var var_downloaded = sse_decode_u_32(deserializer);
var var_conflicts = sse_decode_u_32(deserializer);
var var_skipped = sse_decode_u_32(deserializer);
var var_deletedLocal = sse_decode_u_32(deserializer);
var var_deletedRemote = sse_decode_u_32(deserializer);
var var_durationMs = sse_decode_u_64(deserializer);
return SyncSummaryFfi(uploaded: var_uploaded, downloaded: var_downloaded, conflicts: var_conflicts, skipped: var_skipped, deletedLocal: var_deletedLocal, deletedRemote: var_deletedRemote, durationMs: var_durationMs); }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected BigInt sse_decode_u_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_box_autoadd_sync_config_ffi(SyncConfigFfi self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_sync_config_ffi(self, serializer); }

@protected void sse_encode_cloud_album_check_result_ffi(CloudAlbumCheckResultFfi self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_bool(self.dcimExists, serializer);
sse_encode_bool(self.picturesExists, serializer);
sse_encode_opt_String(self.dcimUri, serializer);
sse_encode_opt_String(self.picturesUri, serializer);
 }

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_String(item, serializer); } }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_opt_String(String? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_String(self, serializer);
                }
                 }

@protected void sse_encode_sync_config_ffi(SyncConfigFfi self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.baseUrl, serializer);
sse_encode_String(self.accessToken, serializer);
sse_encode_String(self.localRoot, serializer);
sse_encode_String(self.remoteRoot, serializer);
sse_encode_String(self.syncMode, serializer);
sse_encode_String(self.conflictStrategy, serializer);
sse_encode_u_32(self.maxConcurrentTransfers, serializer);
sse_encode_u_64(self.bandwidthLimitKbps, serializer);
sse_encode_list_String(self.excludedPaths, serializer);
sse_encode_list_String(self.selectiveDirs, serializer);
 }

@protected void sse_encode_sync_error_ffi(SyncErrorFfi self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case SyncErrorFfi_NotInitialized(): sse_encode_i_32(0, serializer); case SyncErrorFfi_NetworkError(message: final message): sse_encode_i_32(1, serializer); sse_encode_String(message, serializer);
case SyncErrorFfi_DiskFull(needed: final needed,available: final available): sse_encode_i_32(2, serializer); sse_encode_u_64(needed, serializer);
sse_encode_u_64(available, serializer);
case SyncErrorFfi_AuthError(message: final message): sse_encode_i_32(3, serializer); sse_encode_String(message, serializer);
case SyncErrorFfi_ConflictError(count: final count): sse_encode_i_32(4, serializer); sse_encode_u_32(count, serializer);
case SyncErrorFfi_InternalError(message: final message): sse_encode_i_32(5, serializer); sse_encode_String(message, serializer);
  } }

@protected void sse_encode_sync_status_ffi(SyncStatusFfi self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.state, serializer);
sse_encode_u_64(self.syncedFiles, serializer);
sse_encode_u_64(self.totalFiles, serializer);
sse_encode_u_32(self.uploadingCount, serializer);
sse_encode_u_32(self.downloadingCount, serializer);
sse_encode_u_32(self.conflictCount, serializer);
sse_encode_u_32(self.errorCount, serializer);
sse_encode_opt_String(self.lastSyncTime, serializer);
sse_encode_opt_String(self.errorMessage, serializer);
 }

@protected void sse_encode_sync_summary_ffi(SyncSummaryFfi self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_32(self.uploaded, serializer);
sse_encode_u_32(self.downloaded, serializer);
sse_encode_u_32(self.conflicts, serializer);
sse_encode_u_32(self.skipped, serializer);
sse_encode_u_32(self.deletedLocal, serializer);
sse_encode_u_32(self.deletedRemote, serializer);
sse_encode_u_64(self.durationMs, serializer);
 }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }
                }
                
