// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
                    default_stream_sink_codec = SseCodec,
                    default_rust_opaque = RustOpaqueMoi,
                    default_rust_auto_opaque = RustAutoOpaqueMoi,
                );
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -922685216;
            

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__ffi__check_cloud_album_dirs_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "check_cloud_album_dirs", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_base_uri = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::check_cloud_album_dirs(api_base_uri).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__create_cloud_album_dirs_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "create_cloud_album_dirs", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_base_uri = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::create_cloud_album_dirs(api_base_uri).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__dispose_sync_engine_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "dispose_sync_engine", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::dispose_sync_engine().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__force_sync_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "force_sync", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::force_sync().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__get_sync_config_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_sync_config", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::get_sync_config().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__get_sync_status_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_sync_status", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::get_sync_status().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__hydrate_file_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "hydrate_file", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_local_path = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::hydrate_file(api_local_path).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__init_sync_engine_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "init_sync_engine", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::api::ffi_types::SyncConfigFfi>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::init_sync_engine(api_config).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__pause_sync_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "pause_sync", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::pause_sync().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__resume_sync_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "resume_sync", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::resume_sync().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__start_continuous_sync_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "start_continuous_sync", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::start_continuous_sync().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__start_initial_sync_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "start_initial_sync", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::start_initial_sync().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__stop_sync_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "stop_sync", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::stop_sync().await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__sync_album_to_cloud_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "sync_album_to_cloud", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_album_paths = <Vec<String>>::sse_decode(&mut deserializer);
let api_remote_dcim_uri = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::sync_album_to_cloud(api_album_paths, api_remote_dcim_uri).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__update_sync_config_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "update_sync_config", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::api::ffi_types::SyncConfigFfi>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::update_sync_config(api_config).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__api__ffi__update_tokens_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "update_tokens", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_access_token = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, crate::api::ffi_types::SyncErrorFfi>((move || async move {
                         let output_ok = crate::api::ffi::update_tokens(api_access_token).await?;   Ok(output_ok)
                    })().await)
                } })
            }

// Section: dart2rust


                impl SseDecode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();}
                }
                
                impl SseDecode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap() != 0}
                }
                
                impl SseDecode for crate::api::ffi_types::CloudAlbumCheckResultFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_dcimExists = <bool>::sse_decode(deserializer);
let mut var_picturesExists = <bool>::sse_decode(deserializer);
let mut var_dcimUri = <Option<String>>::sse_decode(deserializer);
let mut var_picturesUri = <Option<String>>::sse_decode(deserializer);
return crate::api::ffi_types::CloudAlbumCheckResultFfi{dcim_exists: var_dcimExists, pictures_exists: var_picturesExists, dcim_uri: var_dcimUri, pictures_uri: var_picturesUri};}
                }
                
                impl SseDecode for Vec<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ { ans_.push(<String>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ { ans_.push(<u8>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<String>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for crate::api::ffi_types::SyncConfigFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_baseUrl = <String>::sse_decode(deserializer);
let mut var_accessToken = <String>::sse_decode(deserializer);
let mut var_localRoot = <String>::sse_decode(deserializer);
let mut var_remoteRoot = <String>::sse_decode(deserializer);
let mut var_syncMode = <String>::sse_decode(deserializer);
let mut var_conflictStrategy = <String>::sse_decode(deserializer);
let mut var_maxConcurrentTransfers = <u32>::sse_decode(deserializer);
let mut var_bandwidthLimitKbps = <u64>::sse_decode(deserializer);
let mut var_excludedPaths = <Vec<String>>::sse_decode(deserializer);
let mut var_selectiveDirs = <Vec<String>>::sse_decode(deserializer);
return crate::api::ffi_types::SyncConfigFfi{base_url: var_baseUrl, access_token: var_accessToken, local_root: var_localRoot, remote_root: var_remoteRoot, sync_mode: var_syncMode, conflict_strategy: var_conflictStrategy, max_concurrent_transfers: var_maxConcurrentTransfers, bandwidth_limit_kbps: var_bandwidthLimitKbps, excluded_paths: var_excludedPaths, selective_dirs: var_selectiveDirs};}
                }
                
                impl SseDecode for crate::api::ffi_types::SyncErrorFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut tag_ = <i32>::sse_decode(deserializer);
            match tag_ {0 => { return crate::api::ffi_types::SyncErrorFfi::NotInitialized; }
1 => { let mut var_message = <String>::sse_decode(deserializer);
return crate::api::ffi_types::SyncErrorFfi::NetworkError{message: var_message}; }
2 => { let mut var_needed = <u64>::sse_decode(deserializer);
let mut var_available = <u64>::sse_decode(deserializer);
return crate::api::ffi_types::SyncErrorFfi::DiskFull{needed: var_needed, available: var_available}; }
3 => { let mut var_message = <String>::sse_decode(deserializer);
return crate::api::ffi_types::SyncErrorFfi::AuthError{message: var_message}; }
4 => { let mut var_count = <u32>::sse_decode(deserializer);
return crate::api::ffi_types::SyncErrorFfi::ConflictError{count: var_count}; }
5 => { let mut var_message = <String>::sse_decode(deserializer);
return crate::api::ffi_types::SyncErrorFfi::InternalError{message: var_message}; }
 _ => { unimplemented!(""); }}}
                }
                
                impl SseDecode for crate::api::ffi_types::SyncStatusFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_state = <String>::sse_decode(deserializer);
let mut var_syncedFiles = <u64>::sse_decode(deserializer);
let mut var_totalFiles = <u64>::sse_decode(deserializer);
let mut var_uploadingCount = <u32>::sse_decode(deserializer);
let mut var_downloadingCount = <u32>::sse_decode(deserializer);
let mut var_conflictCount = <u32>::sse_decode(deserializer);
let mut var_errorCount = <u32>::sse_decode(deserializer);
let mut var_lastSyncTime = <Option<String>>::sse_decode(deserializer);
let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
return crate::api::ffi_types::SyncStatusFfi{state: var_state, synced_files: var_syncedFiles, total_files: var_totalFiles, uploading_count: var_uploadingCount, downloading_count: var_downloadingCount, conflict_count: var_conflictCount, error_count: var_errorCount, last_sync_time: var_lastSyncTime, error_message: var_errorMessage};}
                }
                
                impl SseDecode for crate::api::ffi_types::SyncSummaryFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_uploaded = <u32>::sse_decode(deserializer);
let mut var_downloaded = <u32>::sse_decode(deserializer);
let mut var_conflicts = <u32>::sse_decode(deserializer);
let mut var_skipped = <u32>::sse_decode(deserializer);
let mut var_deletedLocal = <u32>::sse_decode(deserializer);
let mut var_deletedRemote = <u32>::sse_decode(deserializer);
let mut var_durationMs = <u64>::sse_decode(deserializer);
return crate::api::ffi_types::SyncSummaryFfi{uploaded: var_uploaded, downloaded: var_downloaded, conflicts: var_conflicts, skipped: var_skipped, deleted_local: var_deletedLocal, deleted_remote: var_deletedRemote, duration_ms: var_durationMs};}
                }
                
                impl SseDecode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap()}
                }
                
                impl SseDecode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
                }
                
                impl SseDecode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i32::<NativeEndian>().unwrap()}
                }
                
                fn pde_ffi_dispatcher_primary_impl(
                    func_id: i32,port: flutter_rust_bridge::for_generated::MessagePort,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                )  {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        1 => wire__crate__api__ffi__check_cloud_album_dirs_impl(port, ptr, rust_vec_len, data_len),
2 => wire__crate__api__ffi__create_cloud_album_dirs_impl(port, ptr, rust_vec_len, data_len),
3 => wire__crate__api__ffi__dispose_sync_engine_impl(port, ptr, rust_vec_len, data_len),
4 => wire__crate__api__ffi__force_sync_impl(port, ptr, rust_vec_len, data_len),
5 => wire__crate__api__ffi__get_sync_config_impl(port, ptr, rust_vec_len, data_len),
6 => wire__crate__api__ffi__get_sync_status_impl(port, ptr, rust_vec_len, data_len),
7 => wire__crate__api__ffi__hydrate_file_impl(port, ptr, rust_vec_len, data_len),
8 => wire__crate__api__ffi__init_sync_engine_impl(port, ptr, rust_vec_len, data_len),
9 => wire__crate__api__ffi__pause_sync_impl(port, ptr, rust_vec_len, data_len),
10 => wire__crate__api__ffi__resume_sync_impl(port, ptr, rust_vec_len, data_len),
11 => wire__crate__api__ffi__start_continuous_sync_impl(port, ptr, rust_vec_len, data_len),
12 => wire__crate__api__ffi__start_initial_sync_impl(port, ptr, rust_vec_len, data_len),
13 => wire__crate__api__ffi__stop_sync_impl(port, ptr, rust_vec_len, data_len),
14 => wire__crate__api__ffi__sync_album_to_cloud_impl(port, ptr, rust_vec_len, data_len),
15 => wire__crate__api__ffi__update_sync_config_impl(port, ptr, rust_vec_len, data_len),
16 => wire__crate__api__ffi__update_tokens_impl(port, ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
                }
                
                fn pde_ffi_dispatcher_sync_impl(
                    func_id: i32,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        
                        _ => unreachable!(),
                    }
                }
                

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::ffi_types::CloudAlbumCheckResultFfi {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.dcim_exists.into_into_dart().into_dart(),
self.pictures_exists.into_into_dart().into_dart(),
self.dcim_uri.into_into_dart().into_dart(),
self.pictures_uri.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ffi_types::CloudAlbumCheckResultFfi {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ffi_types::CloudAlbumCheckResultFfi> for crate::api::ffi_types::CloudAlbumCheckResultFfi {
            fn into_into_dart(self) -> crate::api::ffi_types::CloudAlbumCheckResultFfi {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::ffi_types::SyncConfigFfi {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.base_url.into_into_dart().into_dart(),
self.access_token.into_into_dart().into_dart(),
self.local_root.into_into_dart().into_dart(),
self.remote_root.into_into_dart().into_dart(),
self.sync_mode.into_into_dart().into_dart(),
self.conflict_strategy.into_into_dart().into_dart(),
self.max_concurrent_transfers.into_into_dart().into_dart(),
self.bandwidth_limit_kbps.into_into_dart().into_dart(),
self.excluded_paths.into_into_dart().into_dart(),
self.selective_dirs.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ffi_types::SyncConfigFfi {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ffi_types::SyncConfigFfi> for crate::api::ffi_types::SyncConfigFfi {
            fn into_into_dart(self) -> crate::api::ffi_types::SyncConfigFfi {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::ffi_types::SyncErrorFfi {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {crate::api::ffi_types::SyncErrorFfi::NotInitialized => { [0.into_dart()].into_dart() }
crate::api::ffi_types::SyncErrorFfi::NetworkError{message} => { [1.into_dart(),
message.into_into_dart().into_dart()].into_dart() }
crate::api::ffi_types::SyncErrorFfi::DiskFull{needed,available} => { [2.into_dart(),
needed.into_into_dart().into_dart(),
available.into_into_dart().into_dart()].into_dart() }
crate::api::ffi_types::SyncErrorFfi::AuthError{message} => { [3.into_dart(),
message.into_into_dart().into_dart()].into_dart() }
crate::api::ffi_types::SyncErrorFfi::ConflictError{count} => { [4.into_dart(),
count.into_into_dart().into_dart()].into_dart() }
crate::api::ffi_types::SyncErrorFfi::InternalError{message} => { [5.into_dart(),
message.into_into_dart().into_dart()].into_dart() }
 _ => { unimplemented!(""); }}
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ffi_types::SyncErrorFfi {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ffi_types::SyncErrorFfi> for crate::api::ffi_types::SyncErrorFfi {
            fn into_into_dart(self) -> crate::api::ffi_types::SyncErrorFfi {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::ffi_types::SyncStatusFfi {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.state.into_into_dart().into_dart(),
self.synced_files.into_into_dart().into_dart(),
self.total_files.into_into_dart().into_dart(),
self.uploading_count.into_into_dart().into_dart(),
self.downloading_count.into_into_dart().into_dart(),
self.conflict_count.into_into_dart().into_dart(),
self.error_count.into_into_dart().into_dart(),
self.last_sync_time.into_into_dart().into_dart(),
self.error_message.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ffi_types::SyncStatusFfi {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ffi_types::SyncStatusFfi> for crate::api::ffi_types::SyncStatusFfi {
            fn into_into_dart(self) -> crate::api::ffi_types::SyncStatusFfi {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::ffi_types::SyncSummaryFfi {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.uploaded.into_into_dart().into_dart(),
self.downloaded.into_into_dart().into_dart(),
self.conflicts.into_into_dart().into_dart(),
self.skipped.into_into_dart().into_dart(),
self.deleted_local.into_into_dart().into_dart(),
self.deleted_remote.into_into_dart().into_dart(),
self.duration_ms.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ffi_types::SyncSummaryFfi {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ffi_types::SyncSummaryFfi> for crate::api::ffi_types::SyncSummaryFfi {
            fn into_into_dart(self) -> crate::api::ffi_types::SyncSummaryFfi {
                self
            }
        }

                impl SseEncode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.into_bytes(), serializer);}
                }
                
                impl SseEncode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self as _).unwrap();}
                }
                
                impl SseEncode for crate::api::ffi_types::CloudAlbumCheckResultFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.dcim_exists, serializer);
<bool>::sse_encode(self.pictures_exists, serializer);
<Option<String>>::sse_encode(self.dcim_uri, serializer);
<Option<String>>::sse_encode(self.pictures_uri, serializer);}
                }
                
                impl SseEncode for Vec<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <String>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <u8>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <String>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for crate::api::ffi_types::SyncConfigFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.base_url, serializer);
<String>::sse_encode(self.access_token, serializer);
<String>::sse_encode(self.local_root, serializer);
<String>::sse_encode(self.remote_root, serializer);
<String>::sse_encode(self.sync_mode, serializer);
<String>::sse_encode(self.conflict_strategy, serializer);
<u32>::sse_encode(self.max_concurrent_transfers, serializer);
<u64>::sse_encode(self.bandwidth_limit_kbps, serializer);
<Vec<String>>::sse_encode(self.excluded_paths, serializer);
<Vec<String>>::sse_encode(self.selective_dirs, serializer);}
                }
                
                impl SseEncode for crate::api::ffi_types::SyncErrorFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {match self {crate::api::ffi_types::SyncErrorFfi::NotInitialized => { <i32>::sse_encode(0, serializer);  }
crate::api::ffi_types::SyncErrorFfi::NetworkError{message} => { <i32>::sse_encode(1, serializer); <String>::sse_encode(message, serializer);
 }
crate::api::ffi_types::SyncErrorFfi::DiskFull{needed,available} => { <i32>::sse_encode(2, serializer); <u64>::sse_encode(needed, serializer);
<u64>::sse_encode(available, serializer);
 }
crate::api::ffi_types::SyncErrorFfi::AuthError{message} => { <i32>::sse_encode(3, serializer); <String>::sse_encode(message, serializer);
 }
crate::api::ffi_types::SyncErrorFfi::ConflictError{count} => { <i32>::sse_encode(4, serializer); <u32>::sse_encode(count, serializer);
 }
crate::api::ffi_types::SyncErrorFfi::InternalError{message} => { <i32>::sse_encode(5, serializer); <String>::sse_encode(message, serializer);
 }
 _ => { unimplemented!(""); }}}
                }
                
                impl SseEncode for crate::api::ffi_types::SyncStatusFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.state, serializer);
<u64>::sse_encode(self.synced_files, serializer);
<u64>::sse_encode(self.total_files, serializer);
<u32>::sse_encode(self.uploading_count, serializer);
<u32>::sse_encode(self.downloading_count, serializer);
<u32>::sse_encode(self.conflict_count, serializer);
<u32>::sse_encode(self.error_count, serializer);
<Option<String>>::sse_encode(self.last_sync_time, serializer);
<Option<String>>::sse_encode(self.error_message, serializer);}
                }
                
                impl SseEncode for crate::api::ffi_types::SyncSummaryFfi {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<u32>::sse_encode(self.uploaded, serializer);
<u32>::sse_encode(self.downloaded, serializer);
<u32>::sse_encode(self.conflicts, serializer);
<u32>::sse_encode(self.skipped, serializer);
<u32>::sse_encode(self.deleted_local, serializer);
<u32>::sse_encode(self.deleted_remote, serializer);
<u64>::sse_encode(self.duration_ms, serializer);}
                }
                
                impl SseEncode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self).unwrap();}
                }
                
                impl SseEncode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
                }
                
                impl SseEncode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i32::<NativeEndian>(self).unwrap();}
                }
                


        
        
        #[cfg(not(target_family = "wasm"))]
        mod io {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();


        }
        #[cfg(not(target_family = "wasm"))]
        pub use io::*;
        
        
        /// cbindgen:ignore
        #[cfg(target_family = "wasm")]
        mod web {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;
                use flutter_rust_bridge::for_generated::wasm_bindgen;
                use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;


// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_web!();


        }
        #[cfg(target_family = "wasm")]
        pub use web::*;
        